### ISSUE TITLE
Typescript support will be awesome

### ISSUE THREAD

**Issue by franklixuefei** [jf248/material-ui-enhanced-fields#1]
Hi @jf248 ,

Thanks a lot for your effort in implementing this. I spent hours trying to figure out autocompletion with Chips using Mui TextField, and your implementation fits exactly what I need!

Not sure if you plan to devote any time in converting them into Typescript or add Typescript definitions? I've been working with React + Typescript for my project and would need to rewrite your implementation into Typescript and perhaps remove "react-powerplug" because it is not supported in Typescript either.

Thanks!

**Comment by jf248** [comment]
Thanks @franklixuefei ! No plans at the moment to implement Typescript but happy to accept pull requests for it.

**Comment by franklixuefei** [comment]
@jf248 Thanks! I'll take a stab when I have time.
