### ISSUE TITLE
[Bug] The multiple selection mode is jumpy

### ISSUE THREAD

**Issue by franklixuefei** [jf248/material-ui-enhanced-fields#2]
Repro:
---
if you go to the [basic multiple demo](https://jf248.github.io/material-ui-enhanced-fields/?selectedKind=ComboboxField&selectedStory=basic%20%28multiple%29&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel), and select an item, you will see that the whole input will "jump" down 8 pixels. 

Opinion
---
I think this has something to do with the `withMarginTop` style, `const withMargin = (multiple && selectedItems && selectedItems.length > 0);` and 
<pre>
&lt;TextField
      {...downShiftProps.getInputProps({
        className: classnames({[classes.withMarginTop]: withMargin}),
</pre>
where it says that `withMarginTop` should be applied when it is `multiple` mode with `selectedItems`. I think this was designed to compensate for the floating label, but now if you remove `withMarginTop`, it works just as expected.

Thanks!
Frank

**Comment by jf248** [comment]
Thanks @franklixuefei, fixed in the latest patch.
