### ISSUE TITLE
[Bug] The floating label for the basic multiple demo is not working

### ISSUE THREAD

**Issue by franklixuefei** [jf248/material-ui-enhanced-fields#3]
Repro:
---
Go to the [basic multiple story](https://jf248.github.io/material-ui-enhanced-fields/?selectedKind=ComboboxField&selectedStory=basic%20%28multiple%29&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel), you will see that the floating label is always floated no matter whether there are selected items or not.

I haven't figured out where the problem is. But in your gif demo as below, it seems to work fine.
![demo2](https://user-images.githubusercontent.com/1334982/36959090-14699066-1ff5-11e8-8e7c-1f66d8aad70a.gif)

Thanks!
Frank

**Comment by jf248** [comment]
Thanks @franklixuefei, fixed in the latest patch.
